apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mpms
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mpms
    app.kubernetes.io/part-of: ci1t-830-0099-app
  name: devfile-sample-mpms
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mpms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mpms
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0099-tenant/ci1t-830-0099-app/devfile-sample-mpms@sha256:d8e105f9760cb855ad66c82987ddabfb6a0374e78e5b060dc522dc3a8da80e2c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
